%timeit is a magic function used to measure the time of an operation

In [6]:
L = range(1000)
%timeit [i**2 for i in L]

354 µs ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
import numpy as np

In [7]:
a = np.arange(1000)
%timeit a**2

2.7 µs ± 81.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating Arrays

## 1.1 Manual Construction of arrays

In [17]:
#normal python list
b = [12,2,23,42,23]
print(b)
type(b)

[12, 2, 23, 42, 23]


list

In [13]:
#1-D numpy array
a = np.array([12,2,23,42,23])
print(a)
type(a)

[12  2 23 42 23]


numpy.ndarray

In [21]:
a

array([12,  2, 23, 42, 23])

In [20]:
a.ndim # prints dimenson of array

1

In [22]:
a.shape

(5,)

In [24]:
b = np.array([[1,2,3],[4,5,6]])

In [25]:
b.shape

(2, 3)

In [27]:
b.ndim

2

In term of arrays:- 1-D array is called Vector, 2-D array is called Matrix and 3,4,...,n-D is called Tensor

## 1.2 Functions for creating arrays

Using np.arrange function - Stands for array range

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.arange(1,10,2) #Start, End(exclusive), Step
b

array([1, 3, 5, 7, 9])

Using np.linspace function

In [33]:
a = np.linspace(0,1,6) #Start, End, Number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

Using np.ones and np.zeroes

Using np.ones - used to create n-D matrix of 1s

In [34]:
a = np.ones((2,3,4)) #we pass tuple of dimesions of array to create
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Using np.zeroes - used to create n-D matrix of 0s

In [36]:
a = np.zeros((3,2,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Using np.eye - used to create 2-D identity matrix

In [37]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
a = np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Using np.diag - used to create diagonal matrix 

In [46]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [47]:
np.diag(a)

array([1, 2, 3, 4, 5])

Using np.random.rand and np.random.randn - creates an array of given shape and random samples

In [48]:
#uniform distributed random numbers
a = np.random.rand(4) #generates an arrays of given shape with random values between 0 and 1
a

array([0.66126461, 0.34188194, 0.15577759, 0.08349395])

In [57]:
a = np.random.rand(4,5)
a

array([[0.17594868, 0.41124926, 0.71141536, 0.77990901, 0.44336124],
       [0.23961151, 0.58339837, 0.55461442, 0.32507145, 0.15605237],
       [0.11973953, 0.32452103, 0.57980122, 0.90662698, 0.17644001],
       [0.95456039, 0.94464516, 0.36906444, 0.5279165 , 0.58690854]])

In [58]:
# Standard normal random numbers
a = np.random.randn(3,5,2) # generates an array of given shape with random values between 0 and greater
a

array([[[-0.86106267, -1.22206262],
        [ 1.6317087 ,  0.40944849],
        [ 0.23146761,  0.79242677],
        [ 1.1499042 , -0.38406721],
        [-0.22290908, -1.48206555]],

       [[ 0.74561873, -1.06547024],
        [-0.53555297, -3.5074688 ],
        [-0.0305401 ,  0.55789105],
        [-0.13740337, -0.73162557],
        [ 0.9923134 ,  0.82070748]],

       [[ 0.36228577,  1.59611455],
        [-1.56545537, -0.64346739],
        [-0.99139621,  0.36042119],
        [-1.03102523,  1.75629912],
        [-0.57568264,  1.30038555]]])

# 2. Basic DataTypes

2. vs 2

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
a.dtype

dtype('int32')

In [66]:
a = np.arange(5, dtype = 'float64') # we can explicitly define which data type we want
a

array([0., 1., 2., 3., 4.])

In [67]:
a.dtype

dtype('float64')

In [71]:
#default data type of zeros and ones function is float64
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [72]:
a.dtype

dtype('float64')

In [10]:
d = np.array([1+2j, 2+4j])
d

array([1.+2.j, 2.+4.j])

In [11]:
type(d)

numpy.ndarray

In [12]:
d.dtype

dtype('complex128')

In [14]:
d = np.array([1+2j, 2+4j, True,"hello"])
d.dtype

dtype('<U64')

# 3. Indexing and Slicing

## 3.1 Indexing
 
 The items of an array can be accessed and assigned in the same way as  the other python sequence 
 ###### (eg: list)

In [18]:
a = np.arange(10)
a[5] #indices begin a zero like other python sequences

5

In [31]:
#for multidimensional array arrays, indexes are tuple of integer
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
a[2,2] # row:2 ,col:2

3

In [33]:
a[(4,0)] = 7

In [34]:
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [7, 0, 0, 0, 5]])

## 3.2 Slicing

In [36]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a[1:8:2] # start: end(exclusive): step

array([1, 3, 5, 7])

In [45]:
#we can also combine assignment and slicing
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [47]:
a = np.arange(10)
a[2:7] = 10
a

array([ 0,  1, 10, 10, 10, 10, 10,  7,  8,  9])

In [49]:
a = np.arange(10)
a[1:8:2] = 10
a

array([ 0, 10,  2, 10,  4, 10,  6, 10,  8,  9])

In [54]:
a = np.arange(10)
b = np.array([11,22,33])
a[3:8:2] = b[::-1]
a

array([ 0,  1,  2, 33,  4, 22,  6, 11,  8,  9])

# 4. Copies and Views

A slicing operation creates a view on a original array, which is just a way of acccesing array data.
Thus original array is not copied in the memory it just takes its refrence.
We can use np.shares_memory(aruguments) or np.shares_memory(a,b) to check if two arrays share the memory block

In [75]:
a = np.arange(10)
b = a[::2] # takes a view(refrence) of a
c = a.copy() # forces a copy

np.may_share_memory(a,b) # checks if a and b shares memory

True

In [76]:
np.shares_memory(a,c)

False

In [77]:
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [78]:
a[2] = 22
b[0] = 10
c[5] = 50
print(a)
print(b)
print(c)

[10  1 22  3  4  5  6  7  8  9]
[10 22  4  6  8]
[ 0  1  2  3  4 50  6  7  8  9]


# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with the boolean or integer arrays(masks).

This method is called Fancy Indexing. It creates copies not views

## Using Boolean Mask

In [97]:
a = np.random.randint(0,20,15) #random number starting range , end(exclusive), number of random numbers in the list
a

array([13, 13, 14,  2, 18, 14, 16, 15,  9,  6, 15, 18,  8,  5,  6])

In [98]:
mask = (a%2==0)
mask

array([False, False,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True])

In [99]:
extract_from_a = a[mask]
extract_from_a

array([14,  2, 18, 14, 16,  6, 18,  8,  6])

### Indexing with the mask can be very useful to assign new values to a sub-array

In [102]:
a[mask] = -1
a

array([13, 13, -1, -1, -1, -1, -1, 15,  9, -1, 15, -1, -1,  5, -1])

In [103]:
extract_from_a

array([14,  2, 18, 14, 16,  6, 18,  8,  6])

### Indexing with an array of integer

In [105]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
#Indexing can be done with the array of integers, where the same index is repeated

a[[2,3,2,4,5]]

array([20, 30, 20, 40, 50])

In [109]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [113]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([1,2,3,4,5,6])
print(a)
print()
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4 5 6]


In [114]:
print(a[2][2])
print(a[(2,2)]) # for multidimensional array we can pass indexes of an element in a tuple inside n-D array

11
11


In [118]:
print(b[2,3,4,3]) # suppose we want to print the elements of array using indexes in following order

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [117]:
print(b[[2,3,4,3]]) # we can pass array of indexes inside the array to print desired elements of array in following order

[3 4 5 4]
