In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a+1 #scalar addition

array([2, 3, 4, 5, 6])

In [4]:
a**2

array([ 1,  4,  9, 16, 25])

In [5]:
b = np.ones(5)+1
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [6]:
print(a)
print(b)
a*b

[1 2 3 4 5]
[2. 2. 2. 2. 2.]


array([ 2.,  4.,  6.,  8., 10.])

In [10]:
# matrix multiplication
c = np.diag([1,2,3,4,5])
c[(4,0)] = 9
print(c)
print()
print(c*c) # normal element to element multiplication
print()
print(c.dot(c)) #matrix multipication
print()
print(np.matmul(c,c)) #matrix multipication

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [9 0 0 0 5]]

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [81  0  0  0 25]]

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [54  0  0  0 25]]

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [54  0  0  0 25]]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,5,4,7])
a==b

In [ ]:
a<b

In [ ]:
# array wise comparison

a = np.array([1,2,3,4,5])
b = np.array([2,2,5,4,7])
c = np.array([1,2,3,4,5])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

### Logical Operations

In [ ]:
a = np.array([1,0,0,1,1], bool)
b = np.array([1,1,0,-1,11], dtype=bool)
print(a)
print(b)
np.logical_and(a,b)

In [ ]:
np.logical_xor(a,b)

### Transcendental function

In [ ]:
a = np.arange(5)
np.sin(a)

In [ ]:
np.log(a)

In [ ]:
np.exp(a) #evaluates e^x for the each given input

# Basic Reductions

### Computing Sums

In [ ]:
a = np.array([1,2,3,4,5])
print(np.sum(a))
print(a.sum())

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print()
print(np.sum(a,axis=0)) # columns (first dimension)
print()
print(a.sum(axis=0))
print()
print(np.sum(a,axis=1)) # rows (second dimension)
print()
print(a.sum(axis=1))

### Other reductions

In [ ]:
a = np.array([10,2,71,4,5])
print(a.max()) # min element
print(a.argmax()) #min element index

### Logical Operations

In [ ]:
print( np.all([True, True, False]) ) # Returns True if all the values are True
print( np.all([True, True, True]) )

In [ ]:
print( np.any([True, True, False]) ) # Returns True if any value is True
print( np.any([True, True, True]) )

In [ ]:
a = np.zeros((5,5))
print(a)
print()
print(a==0)
print()
print( np.all(a==0) )


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,5,4,7])
c = np.array([1,2,3,4,5])

((a>b) | (b<=c)).any()

### Statistic

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([[2,2,5,4,7],[1,2,3,4,5]])

np.median(a)

In [ ]:
np.median(b)

In [ ]:
np.median(b,axis=1)

In [ ]:
a.mean()

In [ ]:
a.std() # standard deviation

# Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [ ]:
a = np.arange(0,20,5)
a

In [ ]:
b = np.tile(a, (4,1))
print(b)
b.T #transpose of b

In [ ]:
np.tile(a, (4,2))

In [ ]:
print(a)
print()
print(b)
print()
print(a+b)

In [ ]:
a = np.arange(0,40,10)
a.shape

In [ ]:
a = a[:,np.newaxis] #adds a new axis -> 2-D array
print(a)
a.shape

### Flattening

In [ ]:
a = np.array([[2,2,5,4,7],[1,2,3,4,5]])
a.ravel() #converts 2-D array to 1-D 

In [ ]:
a = np.array([[2,2,5,4,7],[1,2,3,4,5]])
a = a.reshape((10,)) #converts 2-D array to 1-D 
a

In [ ]:
a.reshape((5,2))

#### Note:   When we perform some operations in arrays in numpy. Numpy doesn't returns a copy rather it takes the reference.
 
#### Reshape may also return a copy

In [ ]:
a = np.array([1,2,3,4,5])
a.resize((10,))
a

In [ ]:
a.resize((5,)) # bug

### Sorting Data

In [ ]:
a = np.array([[2,2,5,4,1],[1,2,3,4,5]])
print(a)
print()

np.sort(a,axis=1) # sort and returns value

In [ ]:
a.sort(axis=1) # sort the original array itself
a

In [ ]:
# sort with fancy indexing
a = np.array([[2,2,5,4,1],[1,2,3,4,5]]) 
print(a)
print()
index_of_sorted_elements = np.argsort(a) # returns the array of indexes inplace of sorted elements
index_of_sorted_elements

In [ ]:
a = np.array([2,2,5,4,1])
index_of_sorted_elements = np.argsort(a) # returns the array of indexes inplace of sorted elements
print(index_of_sorted_elements)
print()
a[index_of_sorted_elements]